# Documentation available at https://expeditor.chef.io/docs/getting-started/
---

project:
  alias: train-k8s-container

# https://expeditor.chef.io/docs/integrations/slack/
slack:
  notify_channel: inspec-notify

# https://expeditor.chef.io/docs/integrations/rubygems/
# This publish is triggered by the `built_in:publish_rubygems` artifact_action.
# TODO: Uncomment when ready to publish to rubygems.org
# rubygems:
#   - train-k8s-container

# https://expeditor.chef.io/docs/integrations/github/
github:
  # This deletes the GitHub PR branch after successfully merged into the release branch
  delete_branch_on_merge: true
  # The tag format to use (e.g. v1.0.0)
  version_tag_format: "v{{version}}"
  # allow bumping the minor release via label
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  # allow bumping the major release via label
  major_bump_labels:
    - "Expeditor: Bump Version Major"

release_branches:
  - main:
      # version_constraint: 0.*

pipelines:
  - verify:
      description: Pull Request validation tests
      # public: true # Uncomment to make this pipeline public
  # TODO: Uncomment when ready to implement the coverage pipeline
  # - coverage:
  #     description: Generate test coverage report

changelog:
  rollup_header: Changes not yet released to rubygems.org


# TODO: Uncomment when ready to implement the workload
# subscriptions:
#   # These actions are taken, in order they are specified, anytime a Pull Request is merged.
#   - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
#     actions:
#       - built_in:bump_version:
#           ignore_labels:
#             - "Expeditor: Skip Version Bump"
#             - "Expeditor: Skip All"
#       - bash:.expeditor/update_version.sh:
#           only_if: built_in:bump_version
#       - built_in:update_changelog:
#           ignore_labels:
#             - "Expeditor: Skip Changelog"
#             - "Expeditor: Skip All"
#       - built_in:build_gem:
#           only_if: built_in:bump_version

  # TODO: Uncomment/Modify when ready to promote
  # - workload: project_promoted:{{agent_id}}:*
  #   actions:
  #     - built_in:rollover_changelog
  #     - built_in:publish_rubygems
